apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "booking.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.env }}
  DB_HOST: {{ .Values.postgres.host | quote }}
  DB_PORT: "5432"
  DB_USER: {{ .Values.postgres.user | quote }}
  DB_NAME: {{ .Values.postgres.dbname | quote }}
  MONGO_DB_NAME: {{ .Values.mongodb.dbname | quote }}