apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.global.env }}/microservices/postgres
        property: DB_PASSWORD
    - secretKey: username
      remoteRef:
        key: {{ .Values.global.env }}/microservices/postgres
        property: DB_USER
    - secretKey: host
      remoteRef:
        key: {{ .Values.global.env }}/microservices/postgres
        property: DB_HOST
    - secretKey: port
      remoteRef:
        key: {{ .Values.global.env }}/microservices/postgres
        property: DB_PORT
    - secretKey: dbname
      remoteRef:
        key: {{ .Values.global.env }}/microservices/postgres
        property: DB_NAME