apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "booking.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-auth
            port:
              number: 3000

      - path: /api/bookings
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-book
            port:
              number: 3001

      - path: /api/search
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-search
            port:
              number: 3002

      - path: /api/payments
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-payment
            port:
              number: 3003

      - path: /api/notifications
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-notification
            port:
              number: 3004

      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-frontend
            port:
              number: 80