# default deny all
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# allow ALB → frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-ingress-frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 80
---
# allow all services to talk to each other + DNS + egress to AWS
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-internal
spec:
  podSelector:
    matchLabels:
      {{- include "booking.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "booking.selectorLabels" . | nindent 10 }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "booking.selectorLabels" . | nindent 10 }}
  - to: # DNS
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
  - to: # AWS services (RDS, SQS, Secrets Manager)
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 443
    - port: 5432